name: Release Obsidian plugin

on:
    push:
        tags:
            - "*"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: "latest"
            - name: Build plugin
              run: |
                  bun install
                  bun run build

            - name: Create release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  tag="${GITHUB_REF#refs/tags/}"

                  cd ./build

                  gh release create "$tag" \
                  --generate-notes \
                  --draft \
                  --verify-tag \
                  main.js manifest.json styles.css
